export const dummyProperties = [
  {
    id: "67f7647c197ac559e4089b96",
    agency:{ name: "Havenly Agency", phone:"0123456789", email:"agency@mail.com"},
    title: "Oceanview Oasis Serenity Escape",
    description:
      "Discover a harmonious blend of modern luxury and timeless elegance. Nestled in the heart of this area, our newest residency offers a sanctuary where every detail is meticulously crafted to elevate your lifestyle. From breathtaking architectural designs to unparalleled amenities, each aspect is thoughtfully curated to redefine the meaning of home. Step into a world of sophistication as you explore our spacious and meticulously designed residences, each boasting premium finishes and panoramic views that inspire awe. Whether you seek a serene retreat to unwind or a vibrant community to connect with, Offers an array of lifestyle amenities tailored to your every need.",
    address: "789 Park Lane, New York, USA",
    city: "New York",
    country: "USA",
    propertyType: "House",
    price: 33000,
    facilities: {
      bedrooms: 3,
      bathrooms: 2,
      garages: 1,
    },
    area: 800,
    amenities: ["Balcony", "High-Speed Internet", "Backyard"],
    images: ["/images/img1.png", "/images/pImg2.png", "/images/pImg3.png", "/images/pImg4.png"],
    isAvailable: true,
    createdAt: "2025-04-10T06:26:04.013Z",
    updatedAt: "2025-04-10T06:26:04.013Z",
  },
  {
    id: "67f76452197ac559e4089b8e",
    agency:{ name: "Havenly Agency", phone:"0123456789", email:"agency@mail.com"},
    title: "Mountain Majesty Tranquility Haven",
    description:
      "This villa is a stunning masterpiece of luxury and art. Adorned with two helipads for convenient aerial access, the expansive interiors provide ample space for relaxation and entertainment. The villa offers panoramic sea views that can be enjoyed from multiple vantage points, while the walls are graced with astonishing, bold artworks that add a touch of sophistication and elegance to the entire property. Every detail of this villa exudes opulence and grandeur, making it a truly exceptional and unique residence.",
    address: "301 Sunset Boulevard, Los Angeles, USA",
    city: "Los Angeles",
    country: "USA",
    propertyType: "Apartment",
    price: 99000,
    facilities: {
      bedrooms: 2,
      bathrooms: 2,
      garages: 1,
    },
    area: 500,
    amenities: ["Backyard", "Garage", "Fireplace"],
    images: ["/images/img2.png", "/images/pImg3.png", "/images/pImg4.png", "/images/pImg2.png"],
    isAvailable: true,
    createdAt: "2025-04-10T06:25:22.593Z",
    updatedAt: "2025-04-10T06:25:22.593Z",
  },
  {
    id: "67f76406197ac559e4089b82",
    agency:{ name: "Havenly Agency", phone:"0123456789", email:"agency@mail.com"},
    title: "Urban Elegance Sophistication Haven",
    description:
      "This villa is a stunning masterpiece of luxury and art. Adorned with two helipads for convenient aerial access, the expansive interiors provide ample space for relaxation and entertainment. The villa offers panoramic sea views that can be enjoyed from multiple vantage points, while the walls are graced with astonishing, bold artworks that add a touch of sophistication and elegance to the entire property. Every detail of this villa exudes opulence and grandeur, making it a truly exceptional and unique residence.",
    address: "900 Bay Street, Toronto, Canada",
    city: "Toronto",
    country: "Canada",
    propertyType: "Villa",
    price: 20000,
    facilities: {
      bedrooms: 2,
      bathrooms: 1,
      garages: 1,
    },
    area: 200,
    amenities: ["Fitness Center", "Terrace", "Parking"],
    images: ["/images/img3.png", "/images/pImg4.png", "/images/pImg3.png", "/images/pImg2.png"],
    isAvailable: true,
    createdAt: "2025-04-10T06:24:06.285Z",
    updatedAt: "2025-04-10T06:24:06.285Z",
  },
  {
    id: "67f763d8197ac559e4089b7a",
    agency:{ name: "Havenly Agency", phone:"0123456789", email:"agency@mail.com"},
    title: "Garden Grove Oasis Retreat Haven",
    description:
      "This villa is a stunning masterpiece of luxury and art. Adorned with two helipads for convenient aerial access, the expansive interiors provide ample space for relaxation and entertainment. The villa offers panoramic sea views that can be enjoyed from multiple vantage points, while the walls are graced with astonishing, bold artworks that add a touch of sophistication and elegance to the entire property. Every detail of this villa exudes opulence and grandeur, making it a truly exceptional and unique residence.",
    address: "29 Alexanderplatz, Berlin, Germany",
    city: "Berlin",
    country: "Germany",
    propertyType: "Townhouse",
    price: 33000,
    facilities: {
      bedrooms: 3,
      bathrooms: 2,
      garages: 1,
    },
    area: 500,
    amenities: ["Terrace", "Backyard", "Fitness Center"],
    images: ["/images/img4.png", "/images/pImg2.png", "/images/pImg3.png", "/images/pImg4.png"],
    isAvailable: true,
    createdAt: "2025-04-10T06:23:20.252Z",
    updatedAt: "2025-04-10T06:23:20.252Z",
  },
  {
    id: "67f765aa197ac559e4089b9c",
    agency:{ name: "Havenly Agency", phone:"0123456789", email:"agency@mail.com"},
    title: "Seaside Bliss Modern Retreat",
    description:
      "Experience seaside living with contemporary design and ocean views from every room. Perfect for vacation rentals or permanent residence. Offers panoramic sea views that can be enjoyed from multiple vantage points, while the walls are graced with astonishing, bold artworks that add a touch of sophistication and elegance to the entire property. Every detail of this villa exudes opulence and grandeur, making it a truly exceptional and unique residence.",
    address: "45 Marina Bay, Miami, USA",
    city: "Miami",
    country: "USA",
    propertyType: "House",
    price: 44000,
    facilities: {
      bedrooms: 4,
      bathrooms: 3,
      garages: 2,
    },
    area: 250,
    amenities: ["Swimming Pool", "Balcony", "Private Beach"],
    images: ["/images/img5.png", "/images/pImg3.png", "/images/pImg2.png", "/images/pImg4.png"],
    isAvailable: true,
    createdAt: "2025-04-10T06:27:30.013Z",
    updatedAt: "2025-04-10T06:27:30.013Z",
  },

  {
    id: "67f765f4197ac559e4089ba4",
    agency:{ name: "Havenly Agency", phone:"0123456789", email:"agency@mail.com"},
    title: "Countryside Charm Rustic Escape",
    description:
      "Enjoy a peaceful countryside retreat with spacious gardens, natural wood interiors, and cozy fireplaces. offers panoramic sea views that can be enjoyed from multiple vantage points, while the walls are graced with astonishing, bold artworks that add a touch of sophistication and elegance to the entire property. Every detail of this villa exudes opulence and grandeur, making it a truly exceptional and unique residence.",
    address: "88 Willow Lane, Edinburgh, UK",
    city: "Edinburgh",
    country: "UK",
    propertyType: "Apartment",
    price: 12000,
    facilities: {
      bedrooms: 2,
      bathrooms: 1,
      garages: 1,
    },
    area: 700,
    amenities: ["Garden", "Fireplace", "Parking"],
    images: ["/images/img6.png", "/images/pImg2.png", "/images/pImg3.png", "/images/pImg4.png"],
    isAvailable: true,
    createdAt: "2025-04-10T06:28:50.013Z",
    updatedAt: "2025-04-10T06:28:50.013Z",
  },
];

export const dummyBookingsData = [
    {
        "id": "67f76839994a731e97d3b8ce",
        "user": "username",
        "property": dummyProperties[1],
        "agency": "Agency",
        "checkInDate": "2025-04-30T00:00:00.000Z",
        "checkOutDate": "2025-05-01T00:00:00.000Z",
        "totalPrice": 299,
        "guests": 4,
        "status": "pending",
        "createdAt": "2025-04-10T06:42:01.529Z",
        "updatedAt": "2025-04-10T06:43:54.520Z",
    },
    {
        "id": "67f76829994a731e97d3b8c3",
        "user": "username",
        "property": dummyProperties[0],
        "agency": "Agency",
        "checkInDate": "2025-04-27T00:00:00.000Z",
        "checkOutDate": "2025-04-28T00:00:00.000Z",
        "totalPrice": 399,
        "guests": 3,
        "status": "pending",
        "paymentMethod": "Pay at Check-in",
        "createdAt": "2025-04-10T06:41:45.873Z",
        "updatedAt": "2025-04-10T06:41:45.873Z",
    },
    {
        "id": "67f76810994a731e97d3b8b4",
        "user": "username",
        "property": dummyProperties[3],
        "agency": "Agency",
        "checkInDate": "2025-04-11T00:00:00.000Z",
        "checkOutDate": "2025-04-12T00:00:00.000Z",
        "totalPrice": 199,
        "guests": 3,
        "status": "pending",
        "paymentMethod": "Pay at Check-in",
        "isPaid": true,
        "createdAt": "2025-04-10T06:41:20.501Z",
        "updatedAt": "2025-04-10T06:41:20.501Z",
    }
]
